spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library

mongock:
  runner-type: "ApplicationRunner"
  change-logs-scan-package: ru.otus.spring.hw16.changelog

server:
  port: 8090

jwt:
    secret: AXFzDktew1Lw9Vn8tj4R
    expTime: 1800000

logging:
  level:
    ROOT: INFO
  file:
    name: ./library-app.log

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,logfile,info"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

info:
  app:
    version: "@version@"
    name: "@name@"