spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library

mongock:
  runner-type: "applicationrunner"
  change-logs-scan-package: ru.otus.spring.hw10.changelog

server:
  port: 8090