spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library
  batch:
    job:
      enabled: false
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true