spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library
  batch:
    job:
      enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.xml
logging:
  level:
    ru:
      otus:
        spring:
          hw14:
            job: DEBUG